/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import {
    NetworkFirst,
    StaleWhileRevalidate,
    Strategy,
    StrategyHandler,
} from 'workbox-strategies';
import {
    PrecacheController,
    createHandlerBoundToURL,
    precacheAndRoute,
} from 'workbox-precaching';
import { cacheNames, clientsClaim } from 'workbox-core';

import { ExpirationPlugin } from 'workbox-expiration';
import { registerRoute } from 'workbox-routing';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

const precacheController = new PrecacheController();
self.addEventListener('install', (event) => {
    const plugins = [
        {
            //@ts-ignore
            cacheWillUpdate: ({ event, request, response }) => {
                if (response && response.status && response.status >= 300) {
                    return false;
                }
                return true;
            },
        },
    ];

    event.waitUntil(
        //@ts-ignore
        precacheController.install({ event, plugins })
    );
});

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
    // Return false to exempt requests from being fulfilled by index.html.
    ({ request, url }: { request: Request; url: URL }) => {
        // If this isn't a navigation, skip.
        if (request.mode !== 'navigate') {
            return false;
        }

        // If this is a URL that starts with /_, skip.
        if (url.pathname.startsWith('/_')) {
            return false;
        }

        // If this looks like a URL for a resource, because it contains
        // a file extension, skip.
        if (url.pathname.match(fileExtensionRegexp)) {
            return false;
        }

        // Return true to signal that we want to use the handler.
        return true;
    },
    precacheController.createHandlerBoundToURL(
        process.env.PUBLIC_URL + '/index.html'
    )
);

registerRoute(
    ({ url, sameOrigin }) => sameOrigin && url.pathname === '/api/exercises',
    new NetworkFirst({
        cacheName: 'exercise',
        plugins: [new ExpirationPlugin({ maxEntries: 1 })],
    })
);

registerRoute(
    ({ url, sameOrigin }) =>
        sameOrigin && url.pathname.startsWith('/api/exercise/'),
    new NetworkFirst({
        cacheName: 'exercises',
        plugins: [new ExpirationPlugin({ maxEntries: 50 })],
    })
);

registerRoute(
    ({ url }) => url.host === 'fonts.gstatic.com',
    new StaleWhileRevalidate({
        cacheName: 'google_fonts',
        plugins: [new ExpirationPlugin({ maxEntries: 10 })],
    })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

self.addEventListener('activate', (event) => {
    event.waitUntil(caches.delete(cacheNames.precache));
});

// Any other custom service worker logic can go here.
